project:
  type: book

book:
  title: "Complex Data Visualizaization for Data Science"
  author: "Dr. Junjun Yin"
  date: "3/24/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



